version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: python_app
    restart: always
    env_file:
      - .env
    volumes:
      - ./app:/app
    expose:
      - "5000"
    depends_on:
      - mongo

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
       - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app/static:/usr/share/nginx/html:ro
    depends_on:
      - app

volumes:
  mongo_data:

